log(10)
seq(1,5,0.01)
rep(1,10,5)
round(2.3333,0)
rbinom(10,2,0.4)
?rt
sample(1:10,4,replace = FALSE)
sample(1:10,4,replace = TRUE)
sample(x<-c("TTT","GGGG","JJJJ","HHHHH"),2,replace = TRUE)
fruit <- c("orange", "orange", "apple", "banana", "orange")
fruit
str(fruit)
fruit.number<-factor(fruit)
str(fruit.number)
fruit.number
levels(fruit.number)

gender<-c("female","female","male","female","male","male")
height<-c(168,165,193,165,179,180)
exercise<-c(180,60,150,280,90,200)
survey<-data.frame(gender,height,exercise)
survey
str(survey)
survey$height
survey[,c(1,3)]
survey2<-rbind(survey,c("female",166,150),c("female",165,90))
survey2
age<-c(19,17,17,18,18,19,18,18)
survey2$age<-age
survey2
survey3<-survey2[-c(4,5),]
survey3
colnames(survey3)
colnames(survey3)<-c("gender","height.cm","age","exercising")
survey3

write.csv(survey3,"surveydata.csv")
getwd()
setwd("/Users/burtonlee/RLabs")
getwd()
cardata<-read.csv("fcr.csv",header = TRUE)
str(cardata)
cardata$cylinder<-factor(cardata$cylinder)
cardata$transmission<-factor(cardata$transmission)
cardata$fuel.type<-factor(cardata$fuel.type)
nrow(cardata)
ncol(cardata)
dim(cardata)
head(cardata,25)
mean(cardata$city)
var(cardata$city)     
sd(cardata$city)
min(cardata$city)
max(cardata$city)
median(cardata$city)
quantile(cardata$city)
summary(cardata$city)
summary(cardata$hwy)
summary(cardata$CO2)
summary(cardata)
mean(cardata$CO2)
hist(cardata$city)
hist(cardata$hwy)
hist(cardata$city,xlab = "city",main = "Histogram of city",col = "lightgreen")
hist(cardata$hwy,xlab = "hwy",main = "Histogram of hwy",col = "lightblue")
par(mfrow=c(1,2))
dev.off()
unique(cardata$make)
unique(cardata$fuel.type)
levels(cardata$fuel.type)
levels(cardata$fuel.type)<-list(Diesel="D",Ethanol="E",Regular="X",Premium="z")
levels(cardata$fuel.type)
levels(cardata$transmission) <- list(Automatic = "A", Automated = "AM", AutomaticSS = "AS", Continuous = "AV", Manual = "M")
levels(cardata$transmission)
cyls <- table(cardata$cylinder)
cyls
tran <- table(cardata$transmission)
tran
fuel <- table(cardata$fuel.type)
fuel
par(mfrow = c(1, 3))
barplot(cyls, xlab = "Number of Cylinders", col = "lightcoral")
barplot(tran, xlab = "Transmission", col = "lightcoral")
barplot(fuel, xlab = "Fuel Type", col = "lightcoral")
cardata2 <- subset(cardata, select = c(engine.size, city, hwy, combo, CO2))
cor(cardata2$city, cardata2$CO2)
cor(cardata2)
sapply(cardata2, mean)
sapply(cardata2, median)
plot(cardata$city ~ cardata$engine.size)
plot(city ~ engine.size, data=cardata)
plot(cardata$engine.size, cardata$city)
plot(engine.size, city, data=cardata)
plot(city ~ engine.size, data = cardata)
dev.off()
plot(city ~ engine.size, ylab = "City Fuel", xlab = "Size of Engine", main = "Scatterplot of City Fuel versus Size of Engine",
     pch = 19, col = "blue3", data = cardata)
lines(lowess(cardata$engine.size,cardata$city),col="red",lwd=2)
plot(cardata2)
